# Generated by Django 5.2.7 on 2025-11-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1', models.CharField(max_length=100)),
                ('fighter2', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.CharField(max_length=100)),
                ('bet_amount', models.FloatField(default=100.0)),
                ('result', models.FloatField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelai')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fight')),
            ],
        ),
    ]
