# Generated by Django 5.2.8 on 2025-11-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('boxing', 'Boxing'), ('football', 'Football')], max_length=20)),
                ('date', models.DateField()),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_1', models.CharField(max_length=100)),
                ('participant_2', models.CharField(max_length=100)),
                ('score_1', models.FloatField(blank=True, null=True)),
                ('score_2', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='core.modelai')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.CharField(max_length=100)),
                ('bet_amount', models.FloatField(default=100.0)),
                ('odds', models.FloatField(default=1.5)),
                ('result', models.FloatField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.modelai')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.match')),
            ],
        ),
    ]
