# Generated by Django 5.2.7 on 2025-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelai',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
