# Generated by Django 5.2.7 on 2025-11-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelai')),
            ],
        ),
    ]
