# Generated by Django 5.2.8 on 2025-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_rapidapi_id_alter_match_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='metadata_participant_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='metadata_participant_2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
