# Generated by Django 5.2.7 on 2026-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prediction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
